---
title: "Norwalk background"
author: "Devraj Kori"
date: "9/30/2019"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
require(readxl)
require(openxlsx)
require(reshape2)
require(scales)
require(gridExtra)
library(tidycensus)
#for QWI
library(httr)
library(jsonlite)
library(readr)
library(leaflet)
library(sf)
```

```{r options, echo=FALSE}

state_var<-"CT"
#if only looking at selection of variables for certain categories, change to false
#enter in the state fips code (for QWI), state FIPS codes can be found here: 
state_fips<-"09"

v17<-load_variables(2017,"acs5", cache=TRUE)
```

```{r identify_norwalk_tracts}
#read in norwalk census tracts
options(scipen=999)
norwalk_tracts<-read_csv("Norwalk CTs.csv")%>%
  mutate(GEOID=paste0('0',GEOID))

#create list of vars to pull for Norwalk
demo_stats<-c(Population="B01003_001", 
              White="B03002_003",
              Poverty="B17001_002",
              Median_hh_income="B06011_001")
#pull demo_stats for norwalk at the ct level
norwalk_stats<-get_acs(variables=demo_stats,
                       state="CT",
                       geography="tract",
                       year=2017,
                       geometry=TRUE)%>%
  select(-moe)%>%
  filter(GEOID%in%norwalk_tracts$GEOID)%>%
  spread(key=variable,value=estimate)%>%
  mutate(`Poverty Rate`=Poverty/Population,
         `Pct Non-White`=(Population-White)/Population)
#create color palette

pal <- colorNumeric(palette = "viridis", domain = norwalk_stats$Median_hh_income, n = 23)
sample_popup=data.frame("Travel Est________"=c("Transit Time","First-Mile Dist", "Last-Mile Dist"),
                        "Aquarium___"=c("37 min", ".9 miles", ".3 miles"),
                        "Mall___" =c("43 min", ".5 mile", ".2 miles"),
                        check.names=FALSE)%>%
  kable("html"#, table.attr = 'style = "border-collapse: collapse;"'
        )

norwalk_stats %>%
    st_transform(crs = "+init=epsg:4326") %>%
    leaflet(width = "100%") %>%
    addProviderTiles(provider = "CartoDB.Positron") %>%
     addPolygons(popup = sample_popup,#paste(sep = "<br/>","Aquarium Mean Transit time:37 minutes",
    #             "First mile Distance: .4 miles",
    #             "Last mile Distance: .3 miles"),
                stroke = FALSE,
                smoothFactor = 0,
                fillOpacity = 0.7,
                color = ~ pal(`Median_hh_income`)) %>%
    addLegend("bottomright", 
              pal = pal, 
              values = ~ `Median_hh_income`,
              title = "Transit time by median income",
              opacity = 1)
save(norwalk_stats,file="Norwalk_Transit_Proto_1/norwalk_stats.rData")


```